// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ShrineXamarin
{
	public partial class HomeHeaderView : UIView
	{
        [Outlet]
        public UIKit.UIImageView backgroundImage { get; set; }

        [Outlet]
        public UIKit.UILabel descLabel { get; set; }

        [Outlet]
        public UIKit.UIImageView textLogo { get; set; }

        [Outlet]
        public UIKit.UILabel titleLabel { get; set; }

		public HomeHeaderView (IntPtr handle) : base (handle) {
		}
	}
}
